# Generated by Django 5.0.6 on 2024-05-17 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='multiple_images',
        ),
        migrations.RemoveField(
            model_name='post',
            name='video_url',
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default=1, upload_to='posts/'),
            preserve_default=False,
        ),
    ]
