# Generated by Django 5.0.6 on 2024-05-17 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_post_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='multiple_images',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='posts/')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='base.post')),
            ],
        ),
    ]
