# Generated by Django 5.0.6 on 2024-05-17 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_image_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='multiple_images',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
