# Generated by Django 5.0.6 on 2024-05-21 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_registration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
