# Generated by Django 5.0.6 on 2024-05-24 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_remove_userprofile_email_remove_userprofile_password_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Профиль пользователя', 'verbose_name_plural': 'Профили пользователей'},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='searches',
            field=models.TextField(blank=True, null=True, verbose_name='Поисковые запросы'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(max_length=255, verbose_name='Телефонный номер'),
        ),
    ]
