# Generated by Django 5.0.6 on 2024-05-24 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_userprofile_options_userprofile_searches_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_pic_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL фото профиля'),
        ),
    ]
