# Generated by Django 5.0.6 on 2024-05-27 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_remove_userprofile_profile_pic_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='passwords',
            field=models.CharField(default=1, max_length=255, verbose_name='Пароль'),
            preserve_default=False,
        ),
    ]
