# Generated by Django 5.0.6 on 2024-06-10 07:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_alter_userprofile_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('followers', models.IntegerField()),
                ('following', models.IntegerField()),
                ('biography', models.TextField(blank=True)),
                ('profile_pic_url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='InstagramPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=100, unique=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('caption', models.TextField(blank=True)),
                ('likes', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('instagram_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.instagramprofile')),
            ],
        ),
        migrations.CreateModel(
            name='UserAnalysisHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_count', models.IntegerField()),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('instagram_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.instagramprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
