# Generated by Django 5.0.6 on 2024-06-11 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_remove_useranalysishistory_instagram_profile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('post_count', models.IntegerField(default=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
