# Generated by Django 5.0.6 on 2024-06-29 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_alter_post_description_alter_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user_profile',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
